CUGL: cugl::Matrix Class Reference
cugl::Matrix Class Reference
#include <cugl.h>
Public Member Functions
Matrix ()
Matrix (GL_Matrix r)
Matrix (GLenum mode)
Matrix (const Vector &axis, double theta)
Matrix (const Plane &refl)
Matrix (const Point &lightPos, const Plane &plane)
Matrix (const Quaternion &q)
Matrix (const Vector &u, const Vector &v)
Matrix (const GLfloat m00, const GLfloat m10, const GLfloat m20, const GLfloat m30, const GLfloat m01, const GLfloat m11, const GLfloat m21, const GLfloat m31, const GLfloat m02, const GLfloat m12, const GLfloat m22, const GLfloat m32, const GLfloat m03, const GLfloat m13, const GLfloat m23, const GLfloat m33)
Quaternion quaternion () const
GLfloat * get ()
Matrix transpose () const
GLfloat trace ()
Matrix inv () const
Matrix operator~ () const
void apply () const
Point apply (const Point &p) const
Vector apply (const Vector &v) const
Vector axis () const
double angle () const
GLfloat & operator() (int i, int j)
const GLfloat & operator() (int i, int j) const
void reflect (const Plane &p)
void shadow (const Point &lightPos, const Plane &plane)
Matrix operator+= (const Matrix &rhs)
Matrix operator-= (const Matrix &rhs)
Matrix operator*= (const Matrix &rhs)
Matrix & operator*= (GLfloat s)
Matrix & operator/= (GLfloat s)
Private Attributes
GL_Matrix m
Friends
Matrix operator+ (const Matrix &m, const Matrix &n)
Matrix operator- (const Matrix &m, const Matrix &n)
Matrix operator* (const Matrix &m, const Matrix &n)
Matrix operator* (GLfloat s, const Matrix &m)
Matrix operator* (const Matrix &m, GLfloat s)
Matrix operator/ (const Matrix &m, GLfloat s)
bool operator== (const Matrix &x, const Matrix &y)
bool operator!= (const Matrix &x, const Matrix &y)
std::ostream & operator<< (std::ostream &os, const Matrix &m)
Detailed Description
An instance is a matrix compatible with an OpenGL transformation matrix. An instance of class Matrix is a 4 by 4 matrix with components of type GLfloat. The components are ordered in the same way as an OpenGL matrix (column-row order, for compatibility with FORTRAN).
Note that OpenGL performs matrix calculations very efficiently. As far as possible, construct transformations using sequences of OpenGL matrix operations. Construct and use the matrices here only if OpenGL does not provide the required facilities.
Definition at line 885 of file cugl.h.
Constructor & Destructor Documentation
Matrix() [1/9]
cugl::Matrix::Matrix ()
Construct the identity matrix.
Matrix() [2/9]
cugl::Matrix::Matrix (GL_Matrix r)
Construct a copy of an arbitrary OpenGL matrix.
Matrix() [3/9]
cugl::Matrix::Matrix (GLenum mode) explicit
Construct a copy of an OpenGL projection or model view matrix.
Parameters
mode should be GL_PROJECTION_MATRIX or GL_MODELVIEW_MATRIX.
Report error BAD_MATRIX_MODE and construct identity matrix for other values of mode.
Matrix() [4/9]
cugl::Matrix::Matrix (const Vector & axis, double theta)
Construct a rotation matrix.
Parameters
axis is the axis of rotation.
theta is the magnitude of the rotation.
Note
The angle theta should be in radians (unlike OpenGL, which uses degrees).
Matrix() [5/9]
cugl::Matrix::Matrix (const Plane & refl) inline explicit
Construct a matrix that reflects a point in the given plane. The matrix can be used to simulate a mirror in an OpenGL program. See also Matrix::reflect().
Parameters
refl is the plane of reflection.
Definition at line 2906 of file cugl.h.
References reflect().
Matrix() [6/9]
cugl::Matrix::Matrix (const Point & lightPos, const Plane & plane) inline
Construct a shadow matrix from a point light source and a plane. The matrix transforms an object into its shadow on the given plane. It is your job to ensure that the shadow has the appropriate colour, transparency, etc. The light source may be a local point (w > 0) or a point at infinity (w = 0). See also Matrix::shadow().
Parameters
lightPos is the position of the light source.
plane is the plane onto which the shadow is projected.
Definition at line 2911 of file cugl.h.
References shadow().
Matrix() [7/9]
cugl::Matrix::Matrix (const Quaternion & q) explicit
Construct a rotation matrix from a quaternion.
Precondition
The quaternion must be a unit quaternion.
Matrix() [8/9]
cugl::Matrix::Matrix (const Vector & u, const Vector & v)
Construct the matrix that rotates one vector to another.
Parameters
u is a vector representing an initial orientation.
v is a vector representing the final orientation. The matrix, applied to u, will yield v.
Precondition
The vectors u and v must be unit vectors.
Matrix() [9/9]
cugl::Matrix::Matrix (const GLfloat m00, const GLfloat m10, const GLfloat m20, const GLfloat m30, const GLfloat m01, const GLfloat m11, const GLfloat m21, const GLfloat m31, const GLfloat m02, const GLfloat m12, const GLfloat m22, const GLfloat m32, const GLfloat m03, const GLfloat m13, const GLfloat m23, const GLfloat m33) inline
Construct a matrix from 16 floats.
Definition at line 2916 of file cugl.h.
References m.
Member Function Documentation
angle()
double cugl::Matrix::angle () const
Return the angle (in radians) of a rotation matrix. Report error BAD_ROTATION_MATRIX and leave result undefined, if the matrix is not a rotation.
Returns
the angle (in radians) of a rotation matrix.
apply() [1/3]
void cugl::Matrix::apply () const inline
Multiply the current OpenGL matrix by this matrix.
Definition at line 2953 of file cugl.h.
References m.
apply() [2/3]
Point cugl::Matrix::apply (const Point & p) const inline
Apply this matrix to a point.
Definition at line 2942 of file cugl.h.
References m, cugl::Point::w, cugl::Point::x, cugl::Point::y, and cugl::Point::z.
apply() [3/3]
Vector cugl::Matrix::apply (const Vector & v) const inline
Apply this matrix to a vector.
Definition at line 2978 of file cugl.h.
References m.
axis()
Vector cugl::Matrix::axis () const
Return the axis of a rotation matrix. Report error BAD_ROTATION_MATRIX and leave result undefined, if the matrix is not a rotation.
Returns
the axis of a rotation matrix.
get()
GLfloat * cugl::Matrix::get () inline
Return a pointer to the first element of the matrix. This function may be used in conjunction with glMultMatrix() to apply this matrix to the current OpenGL matrix.
Returns
a pointer to the first element of the matrix.
Definition at line 2958 of file cugl.h.
References m.
inv()
Matrix cugl::Matrix::inv () const
Compute the inverse of this matrix using Gauss-Jordan elimination. If the matrix is singular, report SINGULAR_MATRIX and return the zero matrix. Calculations are performed in double precision because this gives slightly better results. The prefix operator ~ has the same effect.
Returns
the inverse of this matrix.
Referenced by operator~().
operator()() [1/2]
GLfloat & cugl::Matrix::operator() (int i, int j) inline
Return a reference to the element m[i][j] of the matrix.
Precondition
The values of i and j must be in the range [0,3].
Returns
the element m[i][j] of the matrix.
Definition at line 2963 of file cugl.h.
References m.
operator()() [2/2]
const GLfloat & cugl::Matrix::operator() (int i, int j) const inline
Return a reference to the element m[i][j] of the const matrix. This version is used for const instances (m(i,j) cannot appear on the left of =).
Precondition
The values of i and j must be in the range [0,3].
Returns
the element m[i][j] of the matrix.
Definition at line 2968 of file cugl.h.
References m.
operator*=() [1/2]
Matrix cugl::Matrix::operator*= (const Matrix & rhs) inline
Multiply and assign matrices.
Definition at line 3063 of file cugl.h.
operator*=() [2/2]
Matrix & cugl::Matrix::operator*= (GLfloat s) inline
Multiply by scalar and assign.
Definition at line 3010 of file cugl.h.
References m.
operator+=()
Matrix cugl::Matrix::operator+= (const Matrix & rhs) inline
Add and assign matrices.
Definition at line 3033 of file cugl.h.
References m.
operator-=()
Matrix cugl::Matrix::operator-= (const Matrix & rhs) inline
Subtract and assign matrices.
Definition at line 3048 of file cugl.h.
References m.
operator/=()
Matrix & cugl::Matrix::operator/= (GLfloat s) inline
Divide by scalar and assign.
Definition at line 2989 of file cugl.h.
References m.
operator~()
Matrix cugl::Matrix::operator~ () const inline
Return the inverse of this matrix. This provides an alternative syntax for inv().
Returns
the inverse of this matrix.
Definition at line 2973 of file cugl.h.
References inv().
quaternion()
Quaternion cugl::Matrix::quaternion () const
Return the quaternion corresponding to this matrix. This function may report BAD_ROTATION_MATRIX.
Note
The result may be imprecise if the rotation angle is close to 180 degrees.
Precondition
The matrix must be a rotation matrix.
reflect()
void cugl::Matrix::reflect (const Plane & p)
Set the matrix so that it reflects a point in the plane p. The matrix can be used to simulate a mirror in an OpenGL program. See also constructors for class Matrix.
Parameters
p is the plane of reflection.
Referenced by Matrix().
shadow()
void cugl::Matrix::shadow (const Point & lightPos, const Plane & plane)
Set the matrix so that it creates a shadow on the plane p from a light source lightPos. The matrix transforms an object into its shadow on the given plane. It is your job to ensure that the shadow has the appropriate colour, transparency, etc. The point p may be either a local point (w > 0) or a point at infinity (w = 0). See also constructors for class Matrix.
Parameters
lightPos is the position of the light source causing the shadow.
plane is the plane upon which the shadow is cast.
Referenced by Matrix().
trace()
GLfloat cugl::Matrix::trace () inline
Return the trace of this matrix. The trace will include the bottom right element, m[3][3].
Definition at line 986 of file cugl.h.
References m.
transpose()
Matrix cugl::Matrix::transpose () const
Return the transpose of this matrix.
Friends And Related Function Documentation
operator!=
bool operator!= (const Matrix & x, const Matrix & y) friend
Compare two matrices. This function returns false only if corresponding components are exactly equal. Values that are theoretically equal but computed in different ways are likely to be unequal according to this function.
Definition at line 3100 of file cugl.h.
operator* [1/3]
Matrix operator* (const Matrix & m, const Matrix & n) friend
Multiply two matrices.
Definition at line 3069 of file cugl.h.
operator* [2/3]
Matrix operator* (const Matrix & m, GLfloat s) friend
Multiply matrix and scalar.
Definition at line 3118 of file cugl.h.
operator* [3/3]
Matrix operator* (GLfloat s, const Matrix & m) friend
Multiply scalar and matrix.
Definition at line 3109 of file cugl.h.
operator+
Matrix operator+ (const Matrix & m, const Matrix & n) friend
Add two matrices.
Definition at line 3041 of file cugl.h.
operator-
Matrix operator- (const Matrix & m, const Matrix & n) friend
Subtract two matrices.
Definition at line 3056 of file cugl.h.
operator/
Matrix operator/ (const Matrix & m, GLfloat s) friend
Divide by scalar.
Definition at line 3127 of file cugl.h.
operator<<
std::ostream& operator<< (std::ostream & os, const Matrix & m) friend
Write a four-line image of the matrix to the output stream. The current settings of the stream formatting parameters are used. If a width is specified with setw(), it is applied to each element of the matrix, not the matrix as a whole.
operator==
bool operator== (const Matrix & x, const Matrix & y) friend
Compare two matrices. This function returns true only if corresponding components are exactly equal. Values that are theoretically equal but computed in different ways are likely to be unequal according to this function.
Definition at line 3091 of file cugl.h.
Member Data Documentation
m
GL_Matrix cugl::Matrix::m private
The elements of the matrix.
Definition at line 1133 of file cugl.h.
Referenced by apply(), get(), Matrix(), operator()(), operator*=(), operator+=(), operator-=(), operator/=(), and trace().
The documentation for this class was generated from the following file:
/home/serguei/openiss/github/CUGL/include/cugl.h